{
 "title": "AdmiralA",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Users",
    "query": {}
   },
   {
    "name": "Shards",
    "query": {}
   },
   {
    "name": "Rooms",
    "query": "screeps.stats.$Users.$Shards.rooms.*"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Creeps",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "screeps.stats.$Users.$Shards.roomSummary.$Rooms.num_creeps"
    }
   ]
  },
  {
   "title": "Spawner",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "targets": [
    {
     "target": "alias(screeps.stats.$Users.$Shards.roomSummary.$Rooms.spawns_spawning, 'isSpawning', false)"
    },
    {
     "target": "alias(movingAverage(screeps.stats.$Users.$Shards.roomSummary.$Rooms.spawns_spawning, '1hour'), 'averageLoad', false)"
    }
   ]
  },
  {
   "title": "Enemy Creeps",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "screeps.stats.$Users.$Shards.roomSummary.$Rooms.num_enemies"
    }
   ]
  },
  {
   "title": "Storage Energy",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "screeps.stats.$Users.$Shards.roomSummary.$Rooms.storage_energy"
    },
    {
     "target": "alias(movingAverage(screeps.stats.$Users.$Shards.roomSummary.$Rooms.storage_energy, '1hour'), 'MA')"
    }
   ]
  },
  {
   "title": "Container Energy",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "screeps.stats.$Users.$Shards.roomSummary.$Rooms.container_energy"
    }
   ]
  },
  {
   "title": "Spawn Energy",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "asPercent(screeps.stats.$Users.$Shards.roomSummary.$Rooms.energy_avail, 2300)"
    }
   ]
  },
  {
   "title": "Link Energy",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "screeps.stats.$Users.$Shards.roomSummary.$Rooms.link_energy"
    }
   ]
  },
  {
   "title": "Tower Energy",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "screeps.stats.$Users.$Shards.roomSummary.$Rooms.tower_energy"
    }
   ]
  },
  {
   "title": "CPU Bucket",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "alias(screeps.stats.$Users.$Shards.cpu.bucket, 'Bucket')"
    },
    {
     "target": "alias(screeps.stats.$Users.$Shards.cpu.used, 'Used')"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "target": "screeps.stats.$Users.$Shards.memory.used"
    }
   ]
  },
  {
   "title": "GCL",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "screeps.stats.$Users.$Shards.gcl.progress"
    }
   ]
  },
  {
   "title": "Ground Energy",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "screeps.stats.$Users.$Shards.roomSummary.$Rooms.ground_resources.energy"
    }
   ]
  },
  {
   "title": "Worst Road",
   "type": "graph",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(screeps.stats.$Users.$Shards.roomSummary.$Rooms.structure_info.road.min_hits, 'Road minimum hits')"
    }
   ]
  },
  {
   "title": "Worst Container",
   "type": "graph",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "screeps.stats.$Users.$Shards.roomSummary.$Rooms.structure_info.container.min_hits"
    }
   ]
  },
  {
   "title": "Worst Rampart",
   "type": "graph",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(screeps.stats.$Users.$Shards.roomSummary.$Rooms.structure_info.rampart.min_hits, 'Worst Rampart')"
    }
   ]
  },
  {
   "title": "Worst Wall",
   "type": "graph",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(screeps.stats.$Users.$Shards.roomSummary.$Rooms.structure_info.constructedWall.min_hits, 'Worst Wall')"
    }
   ]
  },
  {
   "title": "Controller Downgrade",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "screeps.stats.$Users.$Shards.roomSummary.$Rooms.controller_downgrade"
    }
   ]
  },
  {
   "title": "Controller Progress",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "screeps.stats.$Users.$Shards.roomSummary.$Rooms.controller_progress"
    }
   ]
  },
  {
   "title": "Construction Sites",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "screeps.stats.$Users.$Shards.roomSummary.$Rooms.num_construction_sites"
    }
   ]
  },
  {
   "title": "Mineral Storage",
   "type": "graph",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "screeps.stats.$Users.$Shards.roomSummary.$Rooms.storage_minerals"
    }
   ]
  },
  {
   "title": "Mineral Available",
   "type": "graph",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "screeps.stats.$Users.$Shards.roomSummary.$Rooms.mineral_amount"
    }
   ]
  },
  {
   "title": "Credits",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "screeps.stats.$Users.$Shards.market.credits"
    }
   ]
  },
  {
   "title": "Terminal Energy",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "screeps.stats.$Users.$Shards.roomSummary.$Rooms.terminal_energy"
    }
   ]
  },
  {
   "title": "Terminal Minerals",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "screeps.stats.$Users.$Shards.roomSummary.$Rooms.terminal_minerals"
    }
   ]
  }
 ]
}