{
 "title": "Screeps TS",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "Users",
    "query": {}
   },
   {
    "name": "Shards",
    "query": {}
   },
   {
    "name": "Rooms",
    "query": "screeps.stats.$Users.$Shards.rooms.*"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "screeps.stats.$Users.$Shards.userStats.usedCpu.total"
    }
   ]
  },
  {
   "title": "CPU Usage Monitor",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 9, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(screeps.stats.$Users.$Shards.userStats.usedCpu.intents, 'Intents', false)"
    },
    {
     "target": "alias(screeps.stats.$Users.$Shards.userStats.usedCpu.pathfinding, 'Pathfinding', false)"
    },
    {
     "target": "alias(screeps.stats.$Users.$Shards.userStats.usedCpu.stats, 'Stats', false)"
    },
    {
     "target": "alias(screeps.stats.$Users.$Shards.userStats.usedCpu.total, 'Max', false)"
    },
    {
     "target": "alias(diff(screeps.stats.$Users.$Shards.userStats.usedCpu.total, sum(screeps.stats.$Users.$Shards.userStats.usedCpu.intents, screeps.stats.$Users.$Shards.userStats.usedCpu.pathfinding, screeps.stats.$Users.$Shards.userStats.usedCpu.stats)), 'Other', false)"
    }
   ]
  },
  {
   "title": "Bucket",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 2, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(screeps.stats.$Users.$Shards.userStats.bucket, 'bucket')"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "screeps.stats.$Users.$Shards.userStats.memory"
    }
   ]
  },
  {
   "title": "Total Creeps",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasSub(screeps.stats.$Users.$Shards.rooms.$Rooms.creeps.*, '.*\\.([^\\.]+)$', '$1')"
    }
   ]
  },
  {
   "title": "Enemy Creeps",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "aliasSub(screeps.stats.$Users.$Shards.rooms.$Rooms.hostileCreeps.playerCreeps.perPlayer.*, '.*\\.([^\\.]+)$', '$1')"
    }
   ]
  },
  {
   "title": "Invader Creeps",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "screeps.stats.$Users.$Shards.rooms.$Rooms.hostileCreeps.invaders"
    }
   ]
  },
  {
   "title": "Controller Progress",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "alias(screeps.stats.$Users.$Shards.rooms.$Rooms.rclProgressTotal, 'Total', false)"
    },
    {
     "target": "alias(screeps.stats.$Users.$Shards.rooms.$Rooms.rclProgress, 'Progress', false)"
    }
   ]
  },
  {
   "title": "Enemy Creeps (colonies)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "aliasSub(screeps.stats.$Users.$Shards.rooms.$Rooms.hostileCreepsInColonies.*.playerCreeps.perPlayer.*, '.*\\.([^\\.]+)$', '$1')"
    }
   ]
  },
  {
   "title": "Invader Creeps (Colonies)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "aliasSub(screeps.stats.$Users.$Shards.rooms.$Rooms.hostileCreepsInColonies.*.invaders, '.*\\.(.*)\\.[^.]*$', '$1')"
    }
   ]
  },
  {
   "title": "Storage Energy",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "screeps.stats.$Users.$Shards.roomStats.storageEnergy"
    },
    {
     "target": "alias(movingAverage(screeps.stats.$Users.$Shards.roomStats.storageEnergy, '10min'), 'MA')"
    }
   ]
  },
  {
   "title": "Link Energy",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "screeps.stats.$Users.$Shards.roomSummary.$Rooms.link_energy"
    }
   ]
  },
  {
   "title": "Spawn Energy",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "asPercent(screeps.stats.$Users.$Shards.roomSummary.$Rooms.energy_avail, 2300)"
    }
   ]
  },
  {
   "title": "Container Energy",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "screeps.stats.$Users.$Shards.roomSummary.$Rooms.container_energy"
    }
   ]
  },
  {
   "title": "Tower Energy",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "screeps.stats.$Users.$Shards.roomSummary.$Rooms.tower_energy"
    }
   ]
  },
  {
   "title": "GCL",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "screeps.stats.$Users.$Shards.gcl.progress"
    }
   ]
  },
  {
   "title": "Spawner",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 9, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "targets": [
    {
     "target": "alias(screeps.stats.$Users.$Shards.rooms.$Rooms.spawning, 'isSpawning', false)"
    }
   ]
  },
  {
   "title": "Credits",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 4, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "screeps.stats.$Users.$Shards.market.credits"
    }
   ]
  }
 ]
}